# Generated by Django 4.2.1 on 2023-05-31 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HHPG', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Haushaltsplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('standort', models.CharField(choices=[('Heidenheim', 'Heidenheim'), ('Heilbronn', 'Heilbronn'), ('Karlsruhe', 'Karlsruhe'), ('Lörrach', 'Lörrach'), ('Mannheim', 'Mannheim'), ('Mosbach', 'Mosbach'), ('Bad Mergentheim', 'Bad Mergentheim'), ('Ravensburg', 'Ravensburg'), ('Friedrichshafen', 'Friedrichshafen'), ('Stuttgart / Horb', 'Stuttgart / Horb'), ('Villingen-Schwenningen', 'Villingen-Schwenningen')], max_length=255)),
                ('startjahr', models.PositiveIntegerField()),
                ('autor', models.CharField(max_length=255)),
                ('studierendenzahl', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='haushaltsposten',
            name='haushaltsplan',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='HHPG.haushaltsplan'),
            preserve_default=False,
        ),
    ]
